[book]
authors = ["Khaneliman"]
language = "en"
src = "."
title = "Khanelivim Docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/khaneliman/khanelivim"
site-url = "/"
